config/routes.rb
Rails.application.routes.draw do
  root 'frontend#homepage'
  get '/doctors', :to => 'frontend#doctors'
  get '/doctors/view', :to => 'frontend#doctor_page'

  get '/services/adults', :to => 'frontend#services_adults'
  get '/services/mri', :to => 'frontend#service_mri'
  get '/services/cardiology', :to => 'frontend#service_cardiology'
  get '/services/diagnostics', :to => 'frontend#services_diagnostics'
  get '/services/surgery', :to => 'frontend#services_surgery'
  get '/services/page', :to => 'frontend#service_page'

  get '/about/clients', :to => 'frontend#about_clients'
  get '/about/partners', :to => 'frontend#about_partners'
  get '/about/investors', :to => 'frontend#about_investors'
  get '/about/legal', :to => 'frontend#about_legal'
  get '/about/jobs', :to => 'frontend#about_jobs'

  get '/patients/notes', :to => 'frontend#patients_notes'
  get '/patients/faq', :to => 'frontend#patients_faq'
  get '/patients/legal', :to => 'frontend#patients_legal'

  get '/promos', :to => 'frontend#promos'
  get '/promos/view', :to => 'frontend#promo_view'

  get '/appointment/doctor', :to => 'frontend#appointment_doctor'
  get '/appointment/doctor/success', :to => 'frontend#appointment_doctor_success'
  get '/appointment/diagnostics', :to => 'frontend#appointment_diagnostics'
  get '/appointment/diagnostics/success', :to => 'frontend#appointment_diagnostics_success'

  get '/reviews', :to => 'frontend#reviews'

  get '/blog', :to => 'frontend#blog'
  get '/blog/view', :to => 'frontend#blog_view'
  get '/blog/author', :to => 'frontend#blog_author'

  get '_/city-confirm', :to => 'frontend#city_confirm'

  get 'user/login', :to => 'user#login'
  get 'user/signup', :to => 'user#signup'
  get 'user/signup/sms', :to => 'user#signup_sms'
  get 'user/signup/sms/resent', :to => 'user#signup_sms_resent'
  get 'user/signup/password', :to => 'user#signup_password'
  get 'user/signup/success', :to => 'user#signup_success'
  get 'user/reset_password', :to => 'user#reset_password'
  get 'user/reset_password', :to => 'user#reset_password'
  get 'user/reset_password/sms', :to => 'user#reset_password_sms'
  get 'user/reset_password/sms/resent', :to => 'user#reset_password_sms_resent'
  get 'user/reset_password/change', :to => 'user#reset_password_change'
  get 'user/reset_password/success', :to => 'user#reset_password_success'

  get 'cabinet/appointments', :to => 'user#cabinet_appointments'
  get 'cabinet/doctors', :to => 'user#cabinet_doctors'
  get 'cabinet/profile', :to => 'user#cabinet_profile'
  get 'cabinet/offers', :to => 'user#cabinet_offers'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/frontend_controller.rb
class FrontendController < ApplicationController
  def homepage
  end

  def doctors
  end

  def doctor_page
  end

  def services_adults
  end

  def services_diagnostics
  end

  def services_surgery
  end

  def service_mri
  end

  def service_cardiology
  end

  def service_page
  end

  def about_clients
  end

  def about_partners
  end

  def about_investors
  end

  def about_legal
  end

  def patients_notes
  end

  def patients_faq
  end

  def patients_legal
  end

  def promo_view
  end

  def city_confirm
  end

  def appointment_doctor
  end

  def appointment_doctor_success
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def login
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/frontend/about_investors.html.haml
- @headerBorder = true
- @pageClass = 'aboutPage'

.page-jumbotron.page-jumbotron_overflow-visible-mobile.animation-waypoint
  .container
    %ul.breadcrumbs
      %li.breadcrumbs-item
        %a.breadcrumbs-item__link{:href => root_path} Главная

      %li.breadcrumbs-item
        %a.breadcrumbs-item__link О компании

    .page-jumbotron__container
      %h2.page-jumbotron__header.about-page__jumbotron-header О компании

  .about-page__tabs
    .container.about-page__tabs-container
      = react_component "Tabs/Tabs", props={links: [{title: "Клиентам", href: about_clients_path},
      {title: "Партнерам", href: about_partners_path},
      {title: "Инвесторам", href: about_investors_path, active: true},
      {title: "Соискателям", href: about_jobs_path},
      {title: "Юридическая информация", href: about_legal_path},
      ]}, html_options={class: 'tabs__wrapper'}


.container.about-page__container
  %h3.about-page__header.animation-waypoint Постоянный рост
  %section.about-page__investors-header.animation-waypoint
    Холдинг «МРТ-Эксперт» – одна из крупнейших в России сетей, объединяющая диагностические центры, специализирующиеся
    на магнитно-резонансной томографии и многофункциональные центры, где наряду с МРТ-диагностикой применяются и другие
    авангардные методы распознавания или исключения из диагноза практически любых скрытых патологий.
  .about-page__investors-spacer.animation-waypoint
  %section.about-page__investors-report.animation-waypoint
    %p.about-page__investors-report-text
      Диагностические центры «МРТ-Эксперт» работают в десятках городов России — от Калининграда до Владивостока,
      от Сочи до Мурманска, ведут прием пациентов в Москве и Санкт-Петербурге, Новосибирске, Твери, других городах
      страны.<br/>
      В этом году число центров «МРТ-Эксперт» в России приблизится к пятидесяти.

    .about-page__investors-download
      .about-page__investors-download-icon
      .about-page__investors-download-text
        .about-page__investors-download-label Отчет о финансовых показателях за 2018 год

        %a.about-page__investors-download-button{href: '#'}
          %span Скачать


.ask-question.ask-question_narrow.ask-question_gray
  .container.ask-question__container
    %p.ask-question__header
      Остались вопросы?
    %p.ask-question__paragraph.ask-question__paragraph_narrow
      Наш специалист подскажет какой врач сможет вам помочь
    %a.button.button_large.ask-question__button{:href => '#'} Чат со специалистом

app/views/frontend/about_jobs.haml
- @headerBorder = true
- @pageClass = 'aboutPage'

.page-jumbotron.page-jumbotron_overflow-visible-mobile.animation-waypoint
  .container
    %ul.breadcrumbs
      %li.breadcrumbs-item
        %a.breadcrumbs-item__link{:href => root_path} Главная

      %li.breadcrumbs-item
        %a.breadcrumbs-item__link О компании

    .page-jumbotron__container
      %h2.page-jumbotron__header.about-page__jumbotron-header О компании


  .about-page__tabs
    .container.about-page__tabs-container
      = react_component "Tabs/Tabs", props={links: [{title: "Клиентам", href: about_clients_path},
      {title: "Партнерам", href: about_partners_path },
      {title: "Инвесторам", href: about_investors_path},
      {title: "Соискателям", href: about_jobs_path, active: true},
      {title: "Юридическая информация", href: about_legal_path},
      ]}, html_options={class: 'tabs__wrapper'}

.container.about-page__container.about-page-jobs__container
  %h3.about-page__header.animation-waypoint Твоя карьера в ГК «Эксперт» -&nbsp;движение к успеху!
  %p.about-page-jobs__header-paragraph.animation-waypoint
    ГК «Эксперт» отличает поступательное и динамичное развитие, расширение географического присутствия,
    сети медицинских центров, высокая динамика ключевых показателей.

  %section.about-page-jobs__advantages-section.animation-waypoint
    %h4.about-page__content-header Преимущества работы в компании:
    .dashed-list
      .dashed-list__item
        ГК «Эксперт» — это федеральная сеть диагностических и медицинских центров, осуществляющая профессиональную
        деятельность более чем в 50 городах России.
      .dashed-list__item
        Компания эффективно осуществляет свою деятельность на рынке частной  медицины России с 2007 года.
      .dashed-list__item
        Ведется обучение врачей и рентгенолаборантов за счет компании.
      .dashed-list__item
        Имеется собственный институт повышения квалификации медицинских кадров «Институт Эксперт».
      .dashed-list__item
        Есть собственный сервисный центр «ТехномедЭксперт».
      .dashed-list__item
        Компания предлагает конкурентный уровень дохода и белую зарплату.
      .dashed-list__item
        Оформление по ТК РФ, полный социальный пакет.
      .dashed-list__item
        Карьерный и профессиональный рост.
      .dashed-list__item
        Корпоративные мероприятия.

%section.container.about-page-jobs__team-container
  %img.about-page-jobs__team.animation-waypoint{src: image_path('about/jobs.png'), srcset: "#{image_path('about/jobs@2x.png')} 2x, #{image_path('about/jobs@3x.png')} 3x"}

  .service-page-section-layout_two-columns.about-page-jobs__more-section.animation-waypoint
    %h3.service-page-section__header Подробнее о вакансиях в&nbsp;ГК «Эксперт»
    %div
      .about-page-jobs__more-group
        .about-page__content-header.about-page-jobs__more-header Для студентов и стажеров
        .about-page-jobs__more-paragraph
          Мы даем не только работу, но и знания. ГК «Эксперт» открывает для своих сотрудников новые горизонты и возможности
      .about-page-jobs__more-group
        .about-page__content-header.about-page-jobs__more-header Для соискателей с опытом
        .about-page-jobs__more-paragraph
          Мы ищем людей, способных творить и создавать новое, смелых и решительных, готовить ставить самые амбициозные цели и достигать их

.page-underlay.about-page-jobs__vacancies-section
  .container
    %h3.about-page__header.animation-waypoint Вакансии

    .about-page-jobs__vacancies
      .job-card__wrapper.animation-waypoint
        .job-card
          .job-card__content
            .job-card__title Врач ультразвуковой диагностики
            .job-card__tag Опыт от 2 лет

          .job-card__footer
            .job-card__content
              %a.arrowed-link.job-card__link
                %span.arrowed-link__text Откликнуться
                %span.arrowed-link__arrow
                  = render :partial => '/shared/inline-icons/arrow-right.svg'

      .job-card__wrapper.animation-waypoint
        .job-card
          .job-card__content
            .job-card__title Фельдшер-лаборант
            .job-card__tag Без опыта

          .job-card__footer
            .job-card__content
              %a.arrowed-link.job-card__link
                %span.arrowed-link__text Откликнуться
                %span.arrowed-link__arrow
                  = render :partial => '/shared/inline-icons/arrow-right.svg'

      .job-card__wrapper.animation-waypoint
        .job-card
          .job-card__content
            .job-card__title Врач-кардиолог
            .job-card__tag Опыт от 6 лет

          .job-card__footer
            .job-card__content
              %a.arrowed-link.job-card__link
                %span.arrowed-link__text Откликнуться
                %span.arrowed-link__arrow
                  = render :partial => '/shared/inline-icons/arrow-right.svg'

.container.about-page-jobs__articles-container
  %h3.about-page__header.about-page-jobs__articles-header.animation-waypoint Карьерный рост в ГК «Эксперт»

  .about-page-jobs__article-wrapper.animation-waypoint
    %a.homepage-blog-article.homepage-blog-article_reversed.about-page-jobs__article
      .homepage-blog-article__content
        .homepage-blog-article__tag.homepage-blog-article__tag_indent-b_normal Региональный директор
        %h3.homepage-blog-article__header Оксана Волкова
        %p.homepage-blog-article__description
          Оксана Волкова приступила к обязанностям регионального директора. Теперь она курирует работу ДЦ в Липецке,
          Ельце, Оренбурге и Уфе. Оксана Волкова пришла работать в центр
        .arrowed-link.arrowed-link_blue.homepage-blog-article__arrowed-link{'data-popup': 'job-story-popup'}
          %span.arrowed-link__text Читать
          %span.arrowed-link__arrow
            = render :partial => '/shared/inline-icons/arrow-right.svg'

      %img.homepage-blog-article__image{src: image_path('about/jobs-v-1.png'), srcset: "#{image_path('about/jobs-v-1@2x.png')} 2x, #{image_path('about/jobs-v-1@3x.png')} 3x"}

  .about-page-jobs__article-wrapper.animation-waypoint
    %a.homepage-blog-article.about-page-jobs__article
      .homepage-blog-article__content
        .homepage-blog-article__tag.homepage-blog-article__tag_indent-b_normal Лечимся вместе
        %h3.homepage-blog-article__header Лилия Захарова
        %p.homepage-blog-article__description
          Исполнительным директором «МРТ-Эксперт Новосибирск» стала Лилия Захарова. Она проработала в ГК «Эксперт»
          7,5 лет. Начала свой профессиональный путь в компании одновременно
        .arrowed-link.arrowed-link_blue.homepage-blog-article__arrowed-link{'data-popup': 'job-story-popup'}
          %span.arrowed-link__text Читать
          %span.arrowed-link__arrow
            = render :partial => '/shared/inline-icons/arrow-right.svg'

      %img.homepage-blog-article__image{src: image_path('about/jobs-v-2.png'), srcset: "#{image_path('about/jobs-v-2@2x.png')} 2x, #{image_path('about/jobs-v-2@3x.png')} 3x"}

  .about-page-jobs__article-wrapper.animation-waypoint
    %a.homepage-blog-article.homepage-blog-article_reversed.about-page-jobs__article
      .homepage-blog-article__content
        .homepage-blog-article__tag.homepage-blog-article__tag_indent-b_normal Здоровье
        %h3.homepage-blog-article__header Жаргал Дугаров
        %p.homepage-blog-article__description
          Жаргал Дугаров возглавил медцентр в Томске. В «МРТ-Эксперт Томск» на должность врача-рентгенолога он пришел в
          2011 году. Через 3 года был назначен главным врачом центра.
        .arrowed-link.arrowed-link_blue.homepage-blog-article__arrowed-link{'data-popup': 'job-story-popup'}
          %span.arrowed-link__text Читать
          %span.arrowed-link__arrow
            = render :partial => '/shared/inline-icons/arrow-right.svg'

      %img.homepage-blog-article__image{src: image_path('about/jobs-v-3.png'), srcset: "#{image_path('about/jobs-v-3@2x.png')} 2x, #{image_path('about/jobs-v-3@3x.png')} 3x"}

.ask-question.ask-question_narrow.ask-question_gray
  .container.ask-question__container
    %p.ask-question__header
      Остались вопросы?
    %p.ask-question__paragraph.ask-question__paragraph_narrow
      Наш специалист подскажет какой врач сможет вам помочь
    %a.button.button_large.ask-question__button{:href => '#'} Чат со специалистом

= react_component "Popups/JobStoryPopup", {name: "job-story-popup",
  tag: "Региональный директор", personName: "Лилия Захарова",
  photo: image_path('about/jobs-v-1.png'), photoSrcSet: "#{image_path('about/jobs-v-1@2x.png')} 2x, #{image_path('about/jobs-v-1@3x.png')} 3x",
  text: "Оксана Волкова приступила к обязанностям регионального директора. Теперь она курирует работу ДЦ в Липецке, Ельце, Оренбурге и Уфе. Оксана Волкова пришла работать в центр ООО «МРТ Эксперт Липецк» в марте 2012 года врачом-рентгенологом. В мае 2014 года была назначена главным врачом, а в сентябре 2014 года - исполнительным директором. За 4,5 года управления сначала одним, а потом и двумя диагностическими центрами в Липецке ей удалось создать сплоченную команду, которая регулярно добивалась отличных результатов. С апреля 2019 года Оксана Волкова перешла на должность руководителя региона. Она рассказала, что не планирует останавливаться на достигнутом и продолжит добиваться высоких результатов через командную работу, объединяя людей вокруг себя. Она рассказала, что не планирует останавливаться на достигнутом и продолжит добиваться высоких результатов через командную работу, объединяя людей вокруг себя.",
  }

app/views/frontend/about_legal.html.haml
- @headerBorder = true
- @pageClass = 'aboutPage'

.page-jumbotron.page-jumbotron_overflow-visible-mobile.animation-waypoint
  .container
    %ul.breadcrumbs
      %li.breadcrumbs-item
        %a.breadcrumbs-item__link{:href => root_path} Главная

      %li.breadcrumbs-item
        %a.breadcrumbs-item__link О компании

    .page-jumbotron__container
      %h2.page-jumbotron__header.about-page__jumbotron-header О компании

  .about-page__tabs
    .container.about-page__tabs-container
      = react_component "Tabs/Tabs", props={links: [{title: "Клиентам", href: about_clients_path},
      {title: "Партнерам", href: about_partners_path},
      {title: "Инвесторам", href: about_investors_path},
      {title: "Соискателям", href: about_jobs_path},
      {title: "Юридическая информация", href: about_legal_path, active: true},
      ]}, html_options={class: 'tabs__wrapper'}

.container.about-page__container.about-page__container_legal
  %h3.about-page__header.animation-waypoint Адреса и реквизиты
  %section.about-page-table__section.animation-waypoint
    %h4.about-page-table__header На Арсения Степанова
    .about-page-table__container
      .about-page-table__row
        .about-page-table__row-header Операционная компания
        .about-page-table__row-content ООО «Клиника Эксперт Тверь»
      .about-page-table__row
        .about-page-table__row-header Исполнительный орган
        .about-page-table__row-content ООО «УК МРТ Эксперт» по договору № 56 от 23.07.2016г.
      .about-page-table__row
        .about-page-table__row-header Учредитель (участник)
        .about-page-table__row-content ООО «Барель», Ликандрова И. Г.
      .about-page-table__row
        .about-page-table__row-header ОГРН, дата государственной регистрации
        .about-page-table__row-content 1026901601220 от 29.10.2002г
      .about-page-table__row
        .about-page-table__row-header Место нахождения / почтовый адрес
        .about-page-table__row-content 170001, г.Тверь, ул. Арсения Степанова, дом №2А, обособленное подразделение: г. Тверь, проезд Швейников, 1
      .about-page-table__row
        .about-page-table__row-header Время приема граждан
        .about-page-table__row-content пн-вт: выходной, ср: с 14:00 до 15:00, чт-вс: выходной
      .about-page-table__row
        .about-page-table__row-header Лицензия
        .about-page-table__row-content ЛО-69-01-002198

  %section.about-page-table__section.animation-waypoint
    %h4.about-page-table__header На проезде Швейников
    .about-page-table__container
      .about-page-table__row
        .about-page-table__row-header Операционная компания
        .about-page-table__row-content ООО «Клиника Эксперт Тверь»
      .about-page-table__row
        .about-page-table__row-header Исполнительный орган
        .about-page-table__row-content ООО «УК МРТ Эксперт» по договору № 56 от 23.07.2016г.
      .about-page-table__row
        .about-page-table__row-header Учредитель (участник)
        .about-page-table__row-content ООО «Барель», Ликандрова И. Г.
      .about-page-table__row
        .about-page-table__row-header ОГРН, дата государственной регистрации
        .about-page-table__row-content 1026901601220 от 29.10.2002г
      .about-page-table__row
        .about-page-table__row-header Место нахождения / почтовый адрес
        .about-page-table__row-content 170001, г.Тверь, ул. Арсения Степанова, дом №2А, обособленное подразделение: г. Тверь, проезд Швейников, 1
      .about-page-table__row
        .about-page-table__row-header Время приема граждан
        .about-page-table__row-content пн-вт: выходной, ср: с 14:00 до 15:00, чт-вс: выходной
      .about-page-table__row
        .about-page-table__row-header Лицензия
        .about-page-table__row-content ЛО-69-01-002198

.about-page__container_legal-large
  .container
    %h3.about-page__header.about-page__header_full-width.animation-waypoint Лицензии и сертификаты

    .about-page-licenses
      %img.about-page-licenses__license.animation-waypoint{src: image_url("about/license-01.png"), srcset: "#{image_url("about/license-01@2x.png")} 2x, #{image_url("about/license-01@3x.png")} 3x"}
      %img.about-page-licenses__license.animation-waypoint{src: image_url("about/license-02.png"), srcset: "#{image_url("about/license-02@2x.png")} 2x, #{image_url("about/license-02@3x.png")} 3x"}
      %img.about-page-licenses__license.animation-waypoint{src: image_url("about/license-03.png"), srcset: "#{image_url("about/license-03@2x.png")} 2x, #{image_url("about/license-03@3x.png")} 3x"}
      %img.about-page-licenses__license.animation-waypoint{src: image_url("about/license-04.png"), srcset: "#{image_url("about/license-04@2x.png")} 2x, #{image_url("about/license-04@3x.png")} 3x"}
      %img.about-page-licenses__license.animation-waypoint{src: image_url("about/license-05.png"), srcset: "#{image_url("about/license-05@2x.png")} 2x, #{image_url("about/license-05@3x.png")} 3x"}
      %img.about-page-licenses__license.animation-waypoint{src: image_url("about/license-06.png"), srcset: "#{image_url("about/license-06@2x.png")} 2x, #{image_url("about/license-06@3x.png")} 3x"}
      %img.about-page-licenses__license.animation-waypoint{src: image_url("about/license-07.png"), srcset: "#{image_url("about/license-07@2x.png")} 2x, #{image_url("about/license-07@3x.png")} 3x"}
      %img.about-page-licenses__license.animation-waypoint{src: image_url("about/license-08.png"), srcset: "#{image_url("about/license-08@2x.png")} 2x, #{image_url("about/license-08@3x.png")} 3x"}

.about-page__container_legal-large.about-page__container_legal-large_documents
  .container
    %h3.about-page__header.animation-waypoint Документы

    .files-list.about-page__files-list.animation-waypoint
      .files-list__row
        Соглашение на обработку персональных данных
        %a.files-list__download-button{:href => '#'}
          %span Скачать
      .files-list__row
        Первичный прием: осмотр и консультация
        %a.files-list__download-button{:href => '#'}
          %span Скачать
      .files-list__row
        Прайс-лист
        %a.files-list__download-button{:href => '#'}
          %span Скачать


.ask-question.ask-question_narrow.ask-question_gray
  .container.ask-question__container
    %p.ask-question__header
      Остались вопросы?
    %p.ask-question__paragraph.ask-question__paragraph_narrow
      Наш специалист подскажет какой врач сможет вам помочь
    %a.button.button_large.ask-question__button{:href => '#'} Чат со специалистом

app/views/frontend/city_confirm.haml
- @headerBorder = true

.service-page-section
  .container{style: 'display: flex; justify-content: center'}
    .button.button_large{'data-popup': 'city-confirmation-popup'} Подтвердить город

.service-page-section
  .container{style: 'display: flex; justify-content: center'}
    .button.button_large{'data-popup': 'city-select-popup'} Выбрать город

= render :partial => '/shared/city_confirmation_popup'

app/views/frontend/patients_notes.haml
- @headerBorder = true
- @pageClass = 'patientsPage'

.page-jumbotron.page-jumbotron_overflow-visible-mobile.page-jumbotron_gray-mobile.animation-waypoint
  .container
    %ul.breadcrumbs
      %li.breadcrumbs-item
        %a.breadcrumbs-item__link{:href => root_path} Главная

      %li.breadcrumbs-item
        %a.breadcrumbs-item__link Информация для пациентов

    .page-jumbotron__container
      %h2.page-jumbotron__header.patients-page__jumbotron-header Информация для&nbsp;пациентов

  .patients-page__tabs
    .container.patients-page__tabs-container
      = react_component "Tabs/Tabs", props={links: [{title: "Памятки", href: patients_notes_path, active: true},
      {title: "Вопросы и ответы", href: patients_faq_path},
      {title: "Законодательство", href: patients_legal_path},
      ]}, html_options={class: 'tabs__wrapper'}

.page-underlay.patients-page__page-underlay
  .container
    %h3.patients-page__header.animation-waypoint Памятки к&nbsp;исследованиям
    %p.patients-page__note.animation-waypoint
      Здесь вы можете найти памятки с требованиями к подготовкте исследованиям, рекомендации по их прохождению

    .filters.patients-page__filters-container.animation-waypoint
      = react_component("FiltersRow/SpecializationFilter", props={},html_options={class: 'patients-page__filters'})

    .files-list.patients-page__notes-files-list.animation-waypoint
      .files-list__row
        Подготовка к МРТ позвоночника
        %a.files-list__download-button{:href => '#'}
          %span Скачать
      .files-list__row
        Подготовка к МРТ позвоночника
        %a.files-list__download-button{:href => '#'}
          %span Скачать
      .files-list__row
        Подготовка к МРТ позвоночника
        %a.files-list__download-button{:href => '#'}
          %span Скачать
      .files-list__row
        Подготовка к МРТ головы
        %a.files-list__download-button{:href => '#'}
          %span Скачать
      .files-list__row
        Подготовка к МРТ позвоночника
        %a.files-list__download-button{:href => '#'}
          %span Скачать
      .files-list__row
        Подготовка к МРТ желудка
        %a.files-list__download-button{:href => '#'}
          %span Скачать
      .files-list__row
        Подготовка к МРТ позвоночника
        %a.files-list__download-button{:href => '#'}
          %span Скачать
      .files-list__row
        Подготовка к МРТ желез
        %a.files-list__download-button{:href => '#'}
          %span Скачать


.ask-question.ask-question_narrow.ask-question_with-bottom-border
  .container.ask-question__container
    %p.ask-question__header
      Остались вопросы?
    %p.ask-question__paragraph.ask-question__paragraph_narrow
      Наш специалист подскажет какой врач сможет вам помочь
    %a.button.button_large.ask-question__button{:href => '#'} Чат со специалистом

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Expert
    = csrf_meta_tags
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1"}/

  %body{:class => @pageClass}
    = render :partial => '/shared/layout/header'
    = yield
    = render :partial => '/shared/layout/footer'
    = render :partial => '/shared/city_select_popup'

app/views/shared/_city_confirmation_popup.haml
= react_component "Popups/ConfirmCityPopup", {name: "city-confirmation-popup"}

app/views/shared/_city_select_popup.haml
= react_component "Popups/CitySelectPopup", {name: "city-select-popup"}

app/views/shared/_doctor_question.html.haml
= react_component "Popups/DoctorQuestionPopup", {name: "doctor-question-popup"}

app/views/shared/_doctor_review.html.haml
= react_component "Popups/DoctorReviewPopup", {name: "doctor-review-popup"}

app/views/shared/_services_footer.html.haml
.ask-question.ask-question_narrow.ask-question_with-bottom-border
  .container.ask-question__container
    %p.ask-question__header
      Не нашли нужное направление?
    %p.ask-question__paragraph
      Наш специалист подскажет какой врач сможет вам помочь
    %a.button.button_large.ask-question__button{:href => '#'} Чат со специалистом

app/views/user/reset_password.html.haml
.page-underlay.auth-page__page-underlay
  .auth-box.auth-box_space-h_normal.auth-box_space-t_normal.auth-box_space-b_medium
    %h3.auth-box__header.auth-box__header_align_center.auth-box__header_indent-b_normal
      Восстановление пароля

    .auth-box__form.preload
      .input-group.input-group_indent-b_default
        %label.input-group__label.input-group__label_indent-b_large Номер телефона
        = react_component "PhoneInput/PhoneInput", {className: 'input-group__input_size_large'}
        .input-group__hint.input-group__hint_greyish-brown.auth-box__sms-hint На этот телефон мы вышлем код для восстановления пароля

    .auth-box__controls.preload
      %a.button.button_large.auth-box__primary-button{href: user_reset_password_sms_url} Продолжить